server:
  port: 82


spring:
#  redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-idle: 50
# springsecrity
  security:
    user:
      name: user
      password: 123456


  devtools:
    restart:
      exclude: static/**,public/**
      enabled: true
    #        设置上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: health_backend   #注册中心名称
  registry:
    address: zookeeper://127.0.0.1:2181

#    scan:
#      base-packages: com.zqjy




