server:
  port: 81
mybatis:
#  mapper-locations: classpath:com/zqjy/dao/*.xml

pagehelper:
  helperdialect: mysql # 指定数据库类型
#  reasonable: false
#  params: count=countSql
#  supportmethodsarguments: true

#  supportMethodsArguments: true
#  params: count=countSql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  devtools:
    restart:
      exclude: static/**,public/**
      enabled: false



dubbo:
  application:
    name:  health_service_provider  #注册中心名称
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20887
    name: dubbo
#  scan:
#    base-packages: com.zqjy.service
